### ISSUE TITLE
monitor LightCurve non-fatal warnings and errors on nersc.

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Monitor#41]
While trying to retrieve light curves from nersc @jbkalmbach and I got a non-fatal (for our work) error and warning. Do people know why we are getting these and if they should be ignored?
- When creating the ssh tunnel using the instructions in README:
  `ssh -L 3307:scidb1.nersc.gov:3306 your_username@cori.nersc.gov
  `
  we get the following at nersc:

```
ModuleCmd_Load.c(226):ERROR:105: Unable to locate a modulefile for 'Base-opts'
```

It does not seem to create a problem.

On my laptop I get the following:

```
from desc.monitor import LightCurve
lc = LightCurve()
lcs = lc.build_lightcurve_from_db(3245)
```

At this stage I get the warning: 
`WARNING: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)" [astropy._erfa.core]`
However, it seems to be fine, in that I can at least get the light curve through:

```
lc.lightcurve
```

**Comment by jchiang87** [comment]
The `ErfaWarning` is coming from the `astropy` code that computes UTC dates.  Essentially, it's complaining that the date requested is too far into the future to be computed reliably because the leap seconds that would occur between now and then are uncertain.  See
https://github.com/astropy/astropy/blob/ffc0a89b2c42fd440eb19bcb2f93db90cab3c98b/cextern/erfa/dat.c#L64

The 'Base-opts' complaint is a result of the recent cori upgrade and is occurring because a module that is no longer needed is attempted to be loaded on login.   The NERSC helpdesk has said this can be ignored.

**Comment by rbiswas4** [comment]
Perfect!
